application: urlviewer-hrd
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: mirror.app
  secure: optional

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
