#!/bin/sh

set -e

#compile python

if which update-python-modules >/dev/null 2>&1; then
	update-python-modules  iexpresso.dirs
fi

#configure dovecot

confdir="/etc/dovecot"
if [ ! -d "${confdir}" ]; then
	mkdir -p "${confdir}"
fi

curdate=`date +%y%m%d.%H%M%S`
srcconf=/usr/share/iexpresso/dovecot.conf
conf="${confdir}/dovecot.conf"

#Check if dovecot is installed and what version of it is installed
if which dovecot >/dev/null 2>&1; then
	dcver=`dovecot --version`
	if dpkg --compare-versions "$dcver" '>' '1.2'; then
		srcconf=/usr/share/iexpresso/dovecot-1.2+.conf
	fi
fi

if [ -e "$conf" ]; then
	# when files are equal, exit
	if diff -q $srcconf $conf >/dev/null 2>&1; then
		exit
	fi
	#create a backup
	mv $conf "${conf}-${curdate}"
fi

cp $srcconf ${conf}

#restart
if [ -x "/etc/init.d/dovecot" ]; then
	if [ -x /usr/sbin/invoke-rc.d ]; then
		invoke-rc.d dovecot restart
	else
		/etc/init.d/dovecot restart
	fi
fi
